version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ../:/usr/src/app
    expose:
      - "5000"
    ports:
      - "5000:5000"
      - "9229:9229"
    command: yarn run start:debug

  mysql:
    image: mysql:8.0.23
    expose:
      - "3306"
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - db:/var/lib/mysql/:cached
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/init.sql:/usr/src/app/.docker/mysql/init.sql

volumes:
  db:
