version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    expose:
      - "3306"
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - db:/var/lib/mysql/:cached
      - ./mysql/sql:/docker-entrypoint-initdb.d

volumes:
  db:
